### ISSUE TITLE
Error al ejecutar collectstatic

### ISSUE THREAD

**Issue by eamanu** [eventoL/eventoL#634]
**Describe el error**
Cuando ejecuto collectstastic tiene el siguiente error:

```bash
cd deploy/docker && docker-compose exec -T worker make backend-collectstatic
cd eventol && python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 397, in listdir
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/eventol/front/eventol/static'
make: *** [Makefile:56: backend-collectstatic] Error 1
make: *** [Makefile:245: docker-backend-collectstatic-dev] Error 2
```

**Repoducción del error**
Pasos para reproducir el error:
1. Ejecutar `make collectstatic`
2. Ver error

**Escritorio (complete la siguiente información):**
    - OS: Debian Testing

**Comment by FedeG** [comment]
El error es porque las carpetas de static no existen en el repo, voy a agregar el `mkdir -p` de las carpetas a los comendos para evitar el error
